sudo: required
language: python
cache: pip

python:
  - '3.6'
services:
  - docker
  - redis-server
addons:
  postgresql: '9.6'
  hosts:
    - redis

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.16.1
    - DATABASE_URL=postgres:///localhost:5432/postgres?user=postgres
    - ANSIBLE_HOST_KEY_CHECKING=False
    - ANSIBLE_VAULT_PASSWORD_FILE=.vault_password.txt
    - REDIS_URL=redis://localhost:6379/0
    - CACHE_REDIS_LOCATION=redis://redis:6379/0
    - CHANNELS_REDIS_LOCATION=redis://redis:6379/1
    - CELERY_BROKER_URL=redis://redis:6379/2
    - CELERY_BROKER_BACKEND=redis://redis:6379/3
    - secure: JaOKz0WiL7ukkQ9cfGlnwKQu6KBr5r5rCg7T7T3H+H7G8i4DdgdDaLJLvqM8nxYHkxpVgWAzAljroOuI+fezfOBvmkVyN7y6Co5nwp5yQy8eHvf6gX9+JB/uph4NxjCGjOusNaUuId0v+qBdV2A43yCgnyy5sISoO39vO9dlRN9gWwxseBGXCtf17BuFNXLqASvvQF543KhgNXptzvsz8/kzrCV1GWhPTetH1KUZSF9J9DFdn0lZTJ3CPSpCx1l4eMqW5ZtSzKb6si5n2vXk/Oe7hbKVMdoDIZlvNYf6pUBOb+4zhWPI+JTR0jCDNgbgAm29F1TvcMMs5OKHdnokueFydU6Lw/kqfirjnPwLcp3G3xi6FfyjOHZCRx6MRxoT9Lp6F9OrpZSvTahydM+LjMrUVJbO3q5zqXeFkT+ZTm9BLgj9cEF9cpWrPiQwNPbhdLP2MOxlgYPK36lQ68tYkx2jByl/9Oe/idF5B83Hud4GQF8Nvx6b6jyBKhbU3JTa+sBoH2KhGJ0pu2t6MIoW33SWbrk6VN19JOm9qdQX5vnDR/jn2IpCD5E949DucoZeDQc1L40JRtKID56ZgGQjwH73QnwKQXj+9Yl5UXjTjT0RVQwpRQQdMvOjIhTvDnj/TnITPd/I2NXca8LTdeWO5yIIpWwSBBB2ddbdWHFmgb4=
    - secure: R3OXIF36VY8OXK+J/gddNFw8WP3CoyuwhpRiCGFtIPOlP5z+MkFhkfktzsMjAXI+NMTh+BQm8SFPInULtgko20mbqy7djhZBOM4xsmr7MFbn+pMPHCjUUNbJ8JDbRV9wU52nDWKLW3G05bvFBrN3433j6hhvByAbnmhzYA4Vekm+wyVOy4V5kG9L5LimbrjAtP08hMZ0beXLP1noh+pteC2v6VtzMkW0bZrcx6BAyfeNmrDUYaVW7EXwsx/H2xvRWzSiPqvj5e/mvS5ocBE+4HNaWjw7na5liETa17CkAerSjNcpaP9TqgS5G1TGjA7+EVnoDnQMXm3XwwI/Ciscte8XND6x8+Z52m7uNAR6nnITVbsRU/HtXd8VUIj+5wIkLGyA5vjUmZG5wHgf7yuTtM/4sXZQY9/vEKmQTLSpBX14AWAZa5ODRVpk8vT5idmvsYH9ewUQbFa47MCGolcRTCCI4ljokKac+VNMgKLG48yvKFrXKLnAQhaUiIDJ3zYV2gHkixCFOTEzdt4UsPbYtE74BFuuy+edEPNvJmG0YCaUYiLiZJXHpGg27Bbr3bSPY4tojjGW7ItbNMRYeEi5ONwyg7gT94U6m6CXcWx4nzBWKi5PuuNlaGSml3YQ/14HoSuEJKDWkTX+0AJNuAqEHiPj+D8b8c1svo4sKzQo5B8=


before_install: "./before_install.sh"

install:
  - pip install pipenv
  - pipenv install

jobs:
  include:

    - stage: test
      script: "py.test"
      if: branch = base

    - stage: build
      script: "docker-compose build"
      if: branch = base

    - stage: automerge master
      scrips: "./deploy/scripts/git-merge-push.sh"
      if: branch = base

    - stage: deploy
      script: "./deploy/scripts/deploy.sh"
      if: branch = master

