# Generated by Django 2.0 on 2017-12-29 00:28

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), blank=True, size=None)),
                ('text', models.TextField()),
                ('claimed_hours', models.DecimalField(decimal_places=8, default=0.0, max_digits=20)),
                ('assumed_hours', models.DecimalField(decimal_places=8, default=0.0, max_digits=20)),
                ('blockchain', models.PositiveSmallIntegerField(default=False, verbose_name=[(0, 'None'), (1, 'IPDB')])),
                ('source', models.TextField(blank=True, null=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Comment')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), blank=True, size=None)),
                ('type', models.PositiveSmallIntegerField(default=5, verbose_name=[(0, 'Need'), (1, 'Goal'), (2, 'Idea'), (3, 'Plan'), (4, 'Step'), (5, 'Task')])),
                ('title', models.TextField()),
                ('body', models.TextField(blank=True, null=True)),
                ('blockchain', models.PositiveSmallIntegerField(default=False, verbose_name=[(0, 'None'), (1, 'IPDB')])),
                ('is_draft', models.BooleanField(default=False)),
                ('source', models.TextField(blank=True, null=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='topic_categories', to='meta.Type')),
                ('editors', models.ManyToManyField(blank=True, related_name='topic_editors', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parents', models.ManyToManyField(blank=True, related_name='parent_topics', to='core.Topic')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'ordering': ('-pk',),
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Topic'),
        ),
    ]
